name: EconomyRename
author: DaDevGuy
main: EconomyRename\DaDevGuy\Main
version: 1.0.0
api: [4.0.0]
description: Easy Economy Rename Plugin
depend: 
- BedrockEconomy

permissions:
 economyrename.use:
  default: op